# Usar una imagen de Node.js
FROM node:14

# Crear un directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Instalar PM2
RUN npm install pm2 -g

# Exponer el puerto 4242
EXPOSE 4242

# Iniciar la aplicación con PM2
CMD ["pm2-runtime", "index.js"]