version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '4242:4242'
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8089:8089'
    depends_on:
      - app